//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "appointment")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub appointment_id: String,
    pub appointment_type_id: String,
    pub doctor_id: String,
    pub from: DateTime,
    pub patient_id: String,
    pub room_id: Option<String>,
    pub to: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::appointment_type::Entity",
        from = "Column::AppointmentTypeId",
        to = "super::appointment_type::Column::AppointmentTypeId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AppointmentType,
    #[sea_orm(
        belongs_to = "super::doctor::Entity",
        from = "Column::DoctorId",
        to = "super::doctor::Column::DoctorId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Doctor,
    #[sea_orm(
        belongs_to = "super::patient::Entity",
        from = "Column::PatientId",
        to = "super::patient::Column::PatientId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Patient,
    #[sea_orm(
        belongs_to = "super::room::Entity",
        from = "Column::RoomId",
        to = "super::room::Column::RoomId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Room,
}

impl Related<super::appointment_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppointmentType.def()
    }
}

impl Related<super::doctor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Doctor.def()
    }
}

impl Related<super::patient::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patient.def()
    }
}

impl Related<super::room::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Room.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
