//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "doctor_appointment_type")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub doctor_appointment_type_id: String,
    pub appointment_type_id: Option<String>,
    pub doctor_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::appointment_type::Entity",
        from = "Column::AppointmentTypeId",
        to = "super::appointment_type::Column::AppointmentTypeId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AppointmentType,
    #[sea_orm(
        belongs_to = "super::doctor::Entity",
        from = "Column::DoctorId",
        to = "super::doctor::Column::DoctorId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Doctor,
}

impl Related<super::appointment_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppointmentType.def()
    }
}

impl Related<super::doctor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Doctor.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
