//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub mod prelude;

pub mod appointment;
pub mod appointment_type;
pub mod doctor;
pub mod doctor_appointment_type;
pub mod patient;
pub mod permission;
pub mod person;
pub mod role;
pub mod role_permission;
pub mod room;
pub mod room_appointment_type;
pub mod user;
pub mod user_permission;
