//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::appointment::Entity as Appointment;
pub use super::appointment_type::Entity as AppointmentType;
pub use super::doctor::Entity as Doctor;
pub use super::doctor_appointment_type::Entity as DoctorAppointmentType;
pub use super::patient::Entity as Patient;
pub use super::permission::Entity as Permission;
pub use super::person::Entity as Person;
pub use super::role::Entity as Role;
pub use super::role_permission::Entity as RolePermission;
pub use super::room::Entity as Room;
pub use super::room_appointment_type::Entity as RoomAppointmentType;
pub use super::user::Entity as User;
pub use super::user_permission::Entity as UserPermission;
